[package]
edition = "2021"
name = "aoc2022"
version = "2022.12.12"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.7.0"

[profile.release]
debug = true

[profile.bench]
debug = true
